import type { HomeServiceDetailConfig } from './types';

export const carpentryDetail = {
  slug: 'carpentry',
  metaTitle: 'Carpentry Services | Leads4U',
  metaDescription:
    'Book vetted carpenters for custom woodwork, repairs, and fittings. Upfront quotes, quality materials, and workmanship you can sign off on.',
  heroLead: 'Woodwork built to ',
  heroItalic: 'last',
  heroTail: ', fitted right',
  heroSubheading:
    'Custom woodwork, repairs, and fittings — matched to experienced carpenters who measure twice, finish clean, and respect your timeline.',
  emergencyTitle: 'Loose hinge, broken shutter, or door that won’t close?',
  emergencyBody:
    'Leads4U can route same-day carpentry visits for safety issues and quick make-safe fixes while you plan the full repair.',
  emergencyWhatsAppPrefill: 'URGENT: I need a carpenter today for a door/window or loose fixture safety issue.',
  categorySectionTitle: 'What we cover under Carpentry',
  categoryIntro:
    'Choose the job type that fits — every card uses the same booking flow so you get one clear quote path.',
  categories: [
    {
      title: 'Modular & fitted furniture',
      description: 'Carcass assembly, alignment, and hardware tuning for kitchens, TV units, and study nooks.',
      tags: ['Alignment', 'Hinges', 'Soft-close'],
      icon: 'layers',
      iconWrap: 'bg-[#5D4037]',
    },
    {
      title: 'Doors & windows',
      description: 'Hanging, planing, architrave, and weather-strip fixes for smooth close and clean sightlines.',
      tags: ['Main door', 'French door', 'Architrave'],
      icon: 'doorOpen',
      iconWrap: 'bg-[#6D4C41]',
    },
    {
      title: 'Wardrobes & storage',
      description: 'Sliding systems, shelf spans, and internal organisers fitted for load and daily use.',
      tags: ['Sliding door', 'Loft storage', 'Shelves'],
      icon: 'treePine',
      iconWrap: 'bg-[#4E342E]',
    },
    {
      title: 'Repairs & restoration',
      description: 'Split panels, swollen jambs, squeaks, and water-damaged sections repaired or replaced.',
      tags: ['Patch & fill', 'Rehang', 'Polish'],
      icon: 'hammer',
      iconWrap: 'bg-[#8D6E63]',
    },
    {
      title: 'Kitchen wood & counters',
      description: 'Cut-outs for sinks/hobs, edge banding, and solid-surface trims to manufacturer detail.',
      tags: ['Cut-outs', 'Edge band', 'Seal'],
      icon: 'ruler',
      iconWrap: 'bg-[#795548]',
    },
    {
      title: 'Shelving & partitions',
      description: 'Floating shelves, glass channels, and light partitions with correct anchors for your wall.',
      tags: ['Gypsum frame', 'Stud find', 'Load'],
      icon: 'gitBranch',
      iconWrap: 'bg-[#3E2723]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Repairs & adjustments',
      items: [
        { name: 'Door rehang & shave', desc: 'Fix rub, latch miss, and seasonal swell without wrecking the finish.' },
        { name: 'Window shutter service', desc: 'Slats, cords, and frame fixes for smooth tilt and lock.' },
        { name: 'Furniture tightening', desc: 'Loose joints, wobble, and hardware swap on beds, chairs, and tables.' },
        { name: 'Water damage patch', desc: 'Localised replace + stain match where full panel swap isn’t needed.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'New installs',
      items: [
        { name: 'Skirting & cornice', desc: 'Mitres, scribes, and paint-ready gaps for a sharp joinery look.' },
        { name: 'Custom shelving', desc: 'Span calculations and concealed brackets rated for your books or AV.' },
        { name: 'Partition frames', desc: 'Wood or metal stud prep coordinated with drywall or panel finish.' },
        { name: 'Outdoor wood', desc: 'Deck boards, pergola members, and treated-wood fixes with drainage in mind.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Finishing',
      items: [
        { name: 'Sanding & sealing', desc: 'Progressive grits and compatible sealers for even sheen.' },
        { name: 'Stain & lacquer touch', desc: 'Spot blend on rails and stiles after repair work.' },
        { name: 'Silicone & trim', desc: 'Neat junctions at counters, baths, and windows.' },
        { name: 'Hardware upgrade', desc: 'Handles, locks, and soft-close retrofits fitted square.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Site discipline',
      items: [
        { name: 'Dust control', desc: 'Zip walls / vac assist on occupied homes when agreed in scope.' },
        { name: 'Measure pack', desc: 'Written dimensions and photos left with you before material orders.' },
        { name: 'Waste sort', desc: 'Offcuts bundled; disposal path confirmed in quote.' },
        { name: 'Protect & handover', desc: 'Floors covered; walkthrough checklist on close.' },
      ],
    },
  ],
  prices: [
    { title: 'Visit / assessment', price: '₹399 – ₹799', note: 'Adjusted against labour if you proceed same visit.' },
    { title: 'Door service (hang / shave)', price: '₹899 – ₹2,400', note: 'Per door; hardware extra if supplied.', featured: true },
    { title: 'Shelf / bracket install', price: '₹499 – ₹1,800', note: 'Per linear ft / point; anchors for wall type quoted.' },
    { title: 'Modular touch-up day', price: '₹2,200 – ₹5,500', note: 'Multi-point tune — hinges, gaps, and alignment pass.' },
    { title: 'Wardrobe sliding service', price: '₹1,200 – ₹3,800', note: 'Track clean, roller swap, and door balance.' },
    { title: 'Custom quote projects', price: 'Scope-based', note: 'Full wardrobes and kitchens — itemised BOQ after site measure.' },
  ],
  toolsSectionLead: 'Site-ready kit — accurate cuts and safe installs.',
  tools: [
    { label: 'Laser measure', icon: 'radar' },
    { label: 'Track saw / circular', icon: 'scissors' },
    { label: 'Router & bits', icon: 'wrench' },
    { label: 'Orbital sander', icon: 'layers' },
    { label: 'Brad nailer', icon: 'hammer' },
    { label: 'Level & squares', icon: 'ruler' },
    { label: 'Stud detector', icon: 'radar' },
    { label: 'Dust extractor', icon: 'wind' },
    { label: 'Clamps & dogs', icon: 'wrench' },
    { label: 'PPE & vacuum', icon: 'shield' },
  ],
  guaranteeIntro: 'Leads4U backs carpentry booked on the platform with clear warranty and invoice terms.',
  stepMatchPhrase: 'carpenter',
  step4Closing: 'Signed job sheet + GST bill; leave a rating to keep quality high.',
  footerTitle: 'Ready to Book a Carpenter?',
  footerSubtitle: 'Custom woodwork and repairs without the runaround — get a quote in minutes.',
  primaryCtaLabel: 'Book a Carpenter',
  finePrint: 'No credit card · cancel anytime · partners background-verified',
  faqs: [
    { q: 'Do you supply wood and hardware?', a: 'Partners can source standard timber, boards, and hinges, or work with your material list. Special veneers may need lead time — quoted before order.' },
    { q: 'How long does a typical door fix take?', a: 'Simple shave-and-hang is often 1–2 hours per door. Replacements needing new jambs can run half a day — ETA in the booking.' },
    { q: 'Will there be a lot of dust?', a: 'We plan cutting outdoors or with extraction where possible. For occupied homes, add “dust control” in notes for extra sheeting.' },
    { q: 'Can you match my existing polish?', a: 'Close blend on repairs is standard; perfect match may need sample offcut or door edge swatch.' },
    { q: 'Is dismantle of old furniture included?', a: 'Listed separately if disposal or stair carry is heavy — scope confirmed before spanners turn.' },
    { q: 'What if my wall can’t take load?', a: 'We probe substrate and switch to chemical anchors or spreader plates — changes signed on site if needed.' },
  ],
} satisfies HomeServiceDetailConfig;

export const paintingDetail = {
  slug: 'painting',
  metaTitle: 'Painting Services | Leads4U',
  metaDescription:
    'Interior and exterior painting with a neat finish. Prep, putty, masking, and colour-ready coats from vetted painters on Leads4U.',
  heroLead: 'A finish that’s ',
  heroItalic: 'smooth',
  heroTail: ', start to coat',
  heroSubheading:
    'Interior and exterior painting with neat lines — masking, prep, and clean handover from pros who respect your floors and furniture.',
  emergencyTitle: 'Moving in soon or need a room guest-ready fast?',
  emergencyBody:
    'Leads4U can prioritise tight move-in windows with crew sizing and dry-time planning spelled out up front.',
  emergencyWhatsAppPrefill: 'Hi, I need painting on a tight deadline (move-in / event). Please suggest soonest slots.',
  categorySectionTitle: 'What we cover under Painting',
  categoryIntro: 'Pick the scope — all cards route to the same structured quote so nothing gets lost in chat.',
  categories: [
    {
      title: 'Interior walls & ceilings',
      description: 'Crack chase, putty, primer, and topcoats with uniform sheen and cut-in discipline.',
      tags: ['Putty', 'Primer', '2 coats'],
      icon: 'paintRoller',
      iconWrap: 'bg-[#1565C0]',
    },
    {
      title: 'Wood & metal enamel',
      description: 'Doors, grills, and railings — degrease, etch/prime, and system coats for durability.',
      tags: ['PU', 'Synthetic', 'Anti-rust'],
      icon: 'paintbrush',
      iconWrap: 'bg-[#283593]',
    },
    {
      title: 'Exterior façade',
      description: 'Pressure wash, crack bridge, and weather-rated topcoat cycles suited to your elevation.',
      tags: ['Texture', 'Sheen', 'UV'],
      icon: 'house',
      iconWrap: 'bg-[#0277BD]',
    },
    {
      title: 'Waterproof paint systems',
      description: 'Bath and terrace-adjacent walls with compatible primers and breathable films.',
      tags: ['Damp block', 'Bath', 'Terrace'],
      icon: 'droplets',
      iconWrap: 'bg-[#00695C]',
    },
    {
      title: 'Stencils & feature walls',
      description: 'Geos, stripes, and soft textures with laser level and clean tape breaks.',
      tags: ['Ombre', 'Stripe', 'Stencil'],
      icon: 'layers',
      iconWrap: 'bg-[#6A1B9A]',
    },
    {
      title: 'Touch-up & maintenance',
      description: 'Scuffs, nail pops, and service coats between tenancies or handovers.',
      tags: ['Spot repair', 'Nail pop', 'Service coat'],
      icon: 'spray',
      iconWrap: 'bg-[#455A64]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Surface prep',
      items: [
        { name: 'Washing & degrease', desc: 'Kitchens and trims cleaned so topcoat bites — no fisheyes.' },
        { name: 'Sanding sequence', desc: 'Progressive grits; feather edges on patches.' },
        { name: 'Crack & pop repair', desc: 'Flexible filler on dynamic joints; rigid on plaster.' },
        { name: 'Masking & protection', desc: 'Floors, glass, and AC grills covered; tape tested for pull.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Coating systems',
      items: [
        { name: 'Primer selection', desc: 'Alkyd / acrylic matched to substrate and topcoat line.' },
        { name: 'Ceiling whites', desc: 'Low-splatter rollers; even lap with corrected lighting checks.' },
        { name: 'Colour walls', desc: 'Two full coats default; deep bases quoted for third if needed.' },
        { name: 'Metal care', desc: 'Rust convert + DTM where exposed to weather.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Exterior specifics',
      items: [
        { name: 'Moisture check', desc: 'No coat over active damp — source noted and referred if needed.' },
        { name: 'Scaffold coordination', desc: 'Boom/scaffold slots aligned with society rules.' },
        { name: 'Texture renew', desc: 'Repair patches blended before full face recoat.' },
        { name: 'Silicone & joints', desc: 'Perimeter seal after paint where spec calls for it.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Handover',
      items: [
        { name: 'Touch-up kit', desc: 'Leftover paint labelled and stored as agreed.' },
        { name: 'De-mask pass', desc: 'Slow pull angles to avoid tearing fresh film.' },
        { name: 'Ventilation plan', desc: 'Close windows / fan timing for odour and cure.' },
        { name: 'Walkthrough sign-off', desc: 'Snag list closed before invoice.' },
      ],
    },
  ],
  prices: [
    { title: 'Site visit & shades', price: '₹299 – ₹699', note: 'Digital shade cards + small sample patches optional.' },
    { title: 'Interior per sq ft (std)', price: '₹12 – ₹28 / sq ft', note: 'Includes basic putty + 2 coats; excludes major replaster.', featured: true },
    { title: 'Enamel doors (per side)', price: '₹450 – ₹1,200', note: 'Degrease + prime + enamel system.' },
    { title: 'Exterior façade (per sq ft)', price: '₹18 – ₹42 / sq ft', note: 'Height, texture, and wash cycles affect band.' },
    { title: 'Ceiling only package', price: 'Room-based quote', note: 'Furniture shift + platform time included when listed.' },
    { title: 'Night / weekend premium', price: '10–25%', note: 'Shown before you accept — crew OT and access windows.' },
  ],
  toolsSectionLead: 'Prep-first tools — straight lines and even film.',
  tools: [
    { label: 'HEPA vac sander', icon: 'wind' },
    { label: 'Airless / HVLP', icon: 'spray' },
    { label: 'Laser level', icon: 'radar' },
    { label: 'Moisture meter', icon: 'droplets' },
    { label: 'Extension poles', icon: 'ruler' },
    { label: 'Masking system', icon: 'layers' },
    { label: 'Mixing sticks & sieves', icon: 'filter' },
    { label: 'Drop film & paper', icon: 'layers' },
    { label: 'Scraper & heat gun', icon: 'flame' },
    { label: 'PPE & respirators', icon: 'shield' },
  ],
  guaranteeIntro: 'Painting jobs on Leads4U ship with written scope, GST billing, and rework path if finish misses spec.',
  stepMatchPhrase: 'painter',
  step4Closing: 'Final walkthrough + touch-up list closed; rate your crew.',
  footerTitle: 'Ready to Book a Painter?',
  footerSubtitle: 'Neat interior and exterior finishes — quotes without the chase.',
  primaryCtaLabel: 'Book a Painter',
  finePrint: 'No credit card · cancel anytime · crews verified',
  faqs: [
    { q: 'Is putty and primer included?', a: 'Standard packages include spot putty and primer. Heavy undulation may need full replaster — called out after inspection.' },
    { q: 'Who moves the furniture?', a: 'Light centre shift is included in many packages; heavy items need prior note or extra hands — quoted.' },
    { q: 'How soon can I move back?', a: 'Water-based walls: often 24h light use; enamels and exteriors follow manufacturer recoat tables — shared on job sheet.' },
    { q: 'Do you supply paint?', a: 'Yes — partner rates on major brands, or labour-only with your material list.' },
    { q: 'What about damp patches?', a: 'We won’t lock moisture under film without source fix; waterproofing trade can be booked in parallel.' },
    { q: 'Can you match an old shade?', a: 'Spectro / wet sample on hidden area first; deep colours may need full reface for even match.' },
  ],
} satisfies HomeServiceDetailConfig;

export const electricalDetail = {
  slug: 'electrical',
  metaTitle: 'Electrical Services | Leads4U',
  metaDescription:
    'Safe electrical installations and repairs from verified electricians. Fault finding, DB work, and neat handovers on Leads4U.',
  heroLead: 'Power you can ',
  heroItalic: 'trust',
  heroTail: ', wired right',
  heroSubheading:
    'Safe electrical installations and repairs — DB upgrades, lighting, and fault diagnosis with test results you can file.',
  emergencyTitle: 'Sparking, burning smell, or partial power loss?',
  emergencyBody:
    'Leads4U prioritises shock and fire-risk calls — isolate guidance on phone where safe, then dispatch a licensed partner.',
  emergencyWhatsAppPrefill: 'URGENT: Electrical sparking / burning smell / partial power loss — need electrician ASAP.',
  categorySectionTitle: 'What we cover under Electrical',
  categoryIntro: 'Tap the job type — one booking path for quotes, visits, and invoices.',
  categories: [
    {
      title: 'DB & protection',
      description: 'MCB/RCD upgrades, segregation, labeling, and IR tests before energising.',
      tags: ['DB upgrade', 'RCD', 'Testing'],
      icon: 'bolt',
      iconWrap: 'bg-[#F9A825]',
    },
    {
      title: 'Wiring & points',
      description: 'New circuits, conduit, and point additions with correct derating and routes.',
      tags: ['Conduit', 'Loops', 'Derating'],
      icon: 'gitBranch',
      iconWrap: 'bg-[#F57F17]',
    },
    {
      title: 'Lighting & fans',
      description: 'Pendants, downlights, dimmers, and fan controllers with safe supports.',
      tags: ['LED', 'Dimmer', 'False ceil'],
      icon: 'lightbulb',
      iconWrap: 'bg-[#FFB300]',
    },
    {
      title: 'Appliance circuits',
      description: 'Dedicated lines for AC, oven, hob, and geysers with appropriate breakers.',
      tags: ['AC point', 'Geyser', 'Hob'],
      icon: 'plug',
      iconWrap: 'bg-[#FF8F00]',
    },
    {
      title: 'Fault finding',
      description: 'Trip tracing, neutral issues, and earth faults located with logging tools.',
      tags: ['Trips', 'Earth fault', 'Log'],
      icon: 'zap',
      iconWrap: 'bg-[#E65100]',
    },
    {
      title: 'Compliance & certs',
      description: 'Test sheets, sticker updates, and photo pack for society / insurer handover.',
      tags: ['IR test', 'Loop Zs', 'Photos'],
      icon: 'shield',
      iconWrap: 'bg-[#EF6C00]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Safety first',
      items: [
        { name: 'Isolate & prove dead', desc: 'Lock-out where possible; two-pole testers on every dead check.' },
        { name: 'Cable condition survey', desc: 'Brittle PVC / overloaded rings flagged before conceal.' },
        { name: 'Earthing review', desc: 'Earth electrode / equipotential paths checked on older installs.' },
        { name: 'Arc-risk hotspots', desc: 'Loose terminations tightened; torque per maker spec on gear.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Installations',
      items: [
        { name: 'Switchboard neatening', desc: 'Dressing, ferrules, and heat zones respected inside DB.' },
        { name: 'New point adds', desc: 'Surface or chase routes agreed; patch responsibility in scope.' },
        { name: 'Smart switching', desc: 'Neutral at switch where required for smart modules.' },
        { name: 'Surge options', desc: 'SPD add-on discussed for lightning-prone feeders.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Repairs',
      items: [
        { name: 'Intermittent trips', desc: 'Divide-and-conquer load steps to find the offending leg.' },
        { name: 'Fixture swaps', desc: 'Weight-rated anchors for fans; heat sinks on LED retrofits.' },
        { name: 'Socket replacements', desc: 'Shuttered plates and correct cable term on quick-connects.' },
        { name: 'UPS / inverter tie', desc: 'Changeover interlocks and neutral handling per make.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Documentation',
      items: [
        { name: 'Test readings', desc: 'IR, continuity, and Zs logged on sheet shared with you.' },
        { name: 'Load schedule', desc: 'Updated sticker / chart inside DB door when we alter circuits.' },
        { name: 'Photo as-built', desc: 'Concealed routes shot before close-up for future maintenance.' },
        { name: 'GST invoice', desc: 'Parts serials noted where warranty applies.' },
      ],
    },
  ],
  prices: [
    { title: 'Inspection / fault hour', price: '₹599 – ₹1,200', note: 'First hour; extensions quoted if tracing is deep.' },
    { title: 'Point add (labour)', price: '₹450 – ₹1,100', note: 'Per point ex materials; chase extra.' },
    { title: 'Fan / light replace', price: '₹299 – ₹899', note: 'Like-for-like; new wiring quoted if absent.' },
    { title: 'DB service (12–16 way)', price: '₹2,500 – ₹6,500', note: 'MCB swap, labeling, basic tests — full rewire quoted separately.', featured: true },
    { title: 'AC isolator + point', price: '₹1,200 – ₹2,800', note: 'Cable size per tonnage; includes isolation.' },
    { title: 'Night emergency', price: '1.5× – 2×', note: 'Shown before accept; parts at MRP + margin disclosed.' },
  ],
  toolsSectionLead: 'Calibrated testers — faults found, not guessed.',
  tools: [
    { label: 'Multifunction tester', icon: 'gauge' },
    { label: 'Clamp meter', icon: 'zap' },
    { label: 'Thermal camera', icon: 'thermometer' },
    { label: 'Insulation tester', icon: 'bolt' },
    { label: 'Cable tracer', icon: 'radar' },
    { label: 'Torque driver', icon: 'wrench' },
    { label: 'Label printer', icon: 'layers' },
    { label: 'Rodding set', icon: 'gitBranch' },
    { label: 'PPE & mats', icon: 'shield' },
    { label: 'Extension light', icon: 'lightbulb' },
  ],
  guaranteeIntro: 'Electrical work booked via Leads4U carries documented tests and platform-backed dispute support.',
  stepMatchPhrase: 'electrician',
  step4Closing: 'Test sheet signed; GST invoice emailed — rate the visit.',
  footerTitle: 'Ready to Book an Electrician?',
  footerSubtitle: 'Safe installs and clear fault-finding — book in minutes.',
  primaryCtaLabel: 'Book an Electrician',
  finePrint: 'No credit card · cancel anytime · licensed partners where applicable',
  faqs: [
    { q: 'Will you issue a compliance certificate?', a: 'Partners provide test readings and job completion notes suitable for society and insurer requests; statutory forms depend on local DISCOM rules — ask in booking notes.' },
    { q: 'Do I need to cut walls for new points?', a: 'Chasing is optional and quoted separately; surface conduit is faster in rentals.' },
    { q: 'Can you work with my interior team?', a: 'Yes — share drawings; we coordinate first-fix / second-fix slots.' },
    { q: 'What if the DB is obsolete?', a: 'We’ll photograph and quote a staged upgrade rather than unsafe patching.' },
    { q: 'Are parts genuine?', a: 'OEM or BIS-marked gear preferred; serials on invoice for breakers and RCCBs.' },
    { q: 'Is warranty on labour only?', a: 'Labour warranty is on sheet; manufacturer warranty passes through on parts.' },
  ],
} satisfies HomeServiceDetailConfig;

export const acRepairDetail = {
  slug: 'ac-repair',
  metaTitle: 'AC Repair & Service | Leads4U',
  metaDescription:
    'Cooling issue diagnosis and AC servicing from trained technicians. Gas checks, jet cleaning, and honest part swaps.',
  heroLead: 'Cooling that ',
  heroItalic: 'actually',
  heroTail: ' comes back',
  heroSubheading:
    'Cooling issue diagnosis and AC servicing — deep clean, gas health, and electrical checks so your split or window unit runs quieter and colder.',
  emergencyTitle: 'No cooling on a hot day or water dripping indoors?',
  emergencyBody:
    'Leads4U can slot priority visits for infant/elder homes when you flag health sensitivity in the booking.',
  emergencyWhatsAppPrefill: 'Hi, my AC is not cooling / leaking indoors — need earliest AC technician visit.',
  categorySectionTitle: 'What we cover under AC Repair',
  categoryIntro: 'Select the symptom cluster — pricing bands tighten after the on-site diagnostic.',
  categories: [
    {
      title: 'Jet service & hygiene',
      description: 'Coil fin wash, drain flush, and blower clean for airflow and smell issues.',
      tags: ['Deep clean', 'Drain', 'Filters'],
      icon: 'droplets',
      iconWrap: 'bg-[#0277BD]',
    },
    {
      title: 'Gas & pressure work',
      description: 'Leak sniff, standing pressure, and weighed top-up only where system integrity allows.',
      tags: ['Leak test', 'Top-up', 'Vacuum'],
      icon: 'gauge',
      iconWrap: 'bg-[#0288D1]',
    },
    {
      title: 'Electrical & PCB',
      description: 'Capacitor, relay, sensor, and comms faults on indoor/outdoor units.',
      tags: ['Capacitor', 'Sensor', 'PCB'],
      icon: 'bolt',
      iconWrap: 'bg-[#039BE5]',
    },
    {
      title: 'Mechanical & mounts',
      description: 'Vibration pads, fan balance, and condenser fan motor swaps.',
      tags: ['Vibration', 'Fan motor', 'Mounts'],
      icon: 'wind',
      iconWrap: 'bg-[#039BE5]',
    },
    {
      title: 'Install support',
      description: 'Deinstall/reinstall for shifting, stand correction, and line-set care.',
      tags: ['Shifting', 'Vacuum', 'Torque'],
      icon: 'wrench',
      iconWrap: 'bg-[#00838F]',
    },
    {
      title: 'Performance tune',
      description: 'Superheat/subcool sanity, airflow baffles, and filter upgrade advice.',
      tags: ['Airflow', 'Charge', 'Advice'],
      icon: 'thermometer',
      iconWrap: 'bg-[#006064]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Diagnosis',
      items: [
        { name: 'Temp split check', desc: 'Indoor vs outdoor deltas logged before any gas work.' },
        { name: 'Amp draw profile', desc: 'Compressor and fan loads compared to nameplate.' },
        { name: 'Drain path test', desc: 'Pour test after clean to avoid repeat ceiling stains.' },
        { name: 'Smell source ID', desc: 'Blower vs coil vs drain pan — clean path chosen accordingly.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Service actions',
      items: [
        { name: 'Fin combing', desc: 'Straighten bent fins for static pressure recovery.' },
        { name: 'Evaporator foam wash', desc: 'Manufacturer-safe chemistry; rinse volume controlled.' },
        { name: 'Condenser wash', desc: 'Outdoor coil wash with cover on electronics.' },
        { name: 'Filter service', desc: 'Washable vs disposable path explained.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Repairs',
      items: [
        { name: 'Capacitor upgrade', desc: 'µF match to OEM; start torque verified post swap.' },
        { name: 'Sensor calibration', desc: 'Room vs coil probes checked after replace.' },
        { name: 'Minor leak braze', desc: 'Nitrogen bubble test; no open venting of refrigerant.' },
        { name: 'Pump / float fix', desc: 'Lift stations for ducted drains where gravity is weak.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Honesty guardrails',
      items: [
        { name: 'No guess gas dump', desc: 'Leak not found → we don’t bill mystery top-ups.' },
        { name: 'Compressor triage', desc: 'Wind vs replace economics explained with amps + age.' },
        { name: 'Quote before PCB', desc: 'High-value boards approved in writing pre-fit.' },
        { name: 'Post-service run log', desc: '15-min stable run before sign-off.' },
      ],
    },
  ],
  prices: [
    { title: 'Standard split service', price: '₹499 – ₹899', note: 'Wash + checks; gas extra if needed.', featured: true },
    { title: 'Jet / foam deep clean', price: '₹899 – ₹1,800', note: 'Heavy fouling or smell jobs.' },
    { title: 'Gas top-up (R32/R410A)', price: 'Per gram / kit', note: 'Only after leak test pass or agreed risk note.' },
    { title: 'Capacitor replace', price: '₹450 – ₹1,200', note: 'Includes test run; OEM preferred.' },
    { title: 'PCB / sensor replace', price: 'Part + ₹600 – ₹1,500', note: 'Labour band by accessibility.' },
    { title: 'Deinstall + reinstall', price: '₹1,200 – ₹3,500', note: 'Includes vacuum on reconnect when in scope.' },
  ],
  toolsSectionLead: 'Gauge-first workflow — charge decisions you can follow.',
  tools: [
    { label: 'Manifold gauges', icon: 'gauge' },
    { label: 'Electronic leak detector', icon: 'radar' },
    { label: 'Vacuum pump', icon: 'wind' },
    { label: 'Clamp meter', icon: 'zap' },
    { label: 'Fin comb kit', icon: 'ruler' },
    { label: 'Pressure nitrogen', icon: 'gauge' },
    { label: 'Temp probes', icon: 'thermometer' },
    { label: 'Torque wrenches', icon: 'wrench' },
    { label: 'Wash covers & mats', icon: 'droplets' },
    { label: 'Recovery notes', icon: 'shield' },
  ],
  guaranteeIntro: 'AC jobs on Leads4U include rerun policy for repeat leaks from same joint when flagged within the window on your sheet.',
  stepMatchPhrase: 'AC technician',
  step4Closing: 'Before/after temps shared; GST bill + filter change date noted.',
  footerTitle: 'Ready to Book AC Service?',
  footerSubtitle: 'Diagnosis-first cooling fixes — transparent parts and gas.',
  primaryCtaLabel: 'Book AC Service',
  finePrint: 'No credit card · cancel anytime · technicians rated each visit',
  faqs: [
    { q: 'How often should I service my split AC?', a: 'Typical urban dust: 2× yearly for heavy-use rooms; light bedrooms may stretch to annual with filter self-care.' },
    { q: 'Will service improve cooling?', a: 'If fouling or weak airflow is the cause, yes. If gas is low or compressor weak, we’ll show numbers before spendy parts.' },
    { q: 'Do you refill gas every visit?', a: 'No — only with passing leak test or agreed monitored top-up with return visit window.' },
    { q: 'Can you fix window ACs?', a: 'Yes where parts exist; older R22 units may be replace vs repair economics.' },
    { q: 'Is AMC available?', a: 'Season packs roll out city-wise — ask on WhatsApp for your pincode.' },
    { q: 'What about indoor water leaks?', a: 'Usually drain block or ice-up; we clear and verify slope; insulation gaps quoted if found.' },
  ],
} satisfies HomeServiceDetailConfig;

export const applianceRepairDetail = {
  slug: 'appliance-repair',
  metaTitle: 'Appliance Repair | Leads4U',
  metaDescription:
    'Repairs for major home appliances — washers, fridges, microwaves, geysers — with clear labour + parts quotes on Leads4U.',
  heroLead: 'Appliances ',
  heroItalic: 'back online',
  heroTail: ', fairly priced',
  heroSubheading:
    'Repairs for major home appliances — error codes decoded, boards tested, and mechanical wear fixed with OEM-leaning parts where possible.',
  emergencyTitle: 'Water leak from washer or fridge not cooling before a trip?',
  emergencyBody:
    'Flag “active leak / spoiling food” in booking — we’ll try to slot same-day where parts vans overlap your area.',
  emergencyWhatsAppPrefill: 'URGENT: Appliance leaking or fridge not cooling — need technician today if possible.',
  categorySectionTitle: 'What we cover under Appliance Repair',
  categoryIntro: 'Choose the appliance family — diagnostics fee policy is stated before you confirm.',
  categories: [
    {
      title: 'Washing machines',
      description: 'Drain errors, bearings, inlet valves, and door interlocks across top/front load.',
      tags: ['Drain pump', 'Inlet', 'Door lock'],
      icon: 'droplets',
      iconWrap: 'bg-[#37474F]',
    },
    {
      title: 'Refrigerators',
      description: 'No cool, ice maker faults, defrost loops, and fan noise on frost-free units.',
      tags: ['Gas loop', 'Defrost', 'Fan'],
      icon: 'refrigerator',
      iconWrap: 'bg-[#455A64]',
    },
    {
      title: 'Microwave & oven',
      description: 'Magnetron-related tripping, interlocks, and convection element paths.',
      tags: ['Interlock', 'HV fuse', 'Element'],
      icon: 'zap',
      iconWrap: 'bg-[#546E7A]',
    },
    {
      title: 'Geysers & water heaters',
      description: 'Element, thermostat, safety valve, and earthing review on wet installs.',
      tags: ['Element', 'Thermostat', 'ELCB'],
      icon: 'bath',
      iconWrap: 'bg-[#607D8B]',
    },
    {
      title: 'Dishwashers',
      description: 'Wash pump, turbidity, and inlet/regeneration faults on freestanding units.',
      tags: ['Wash pump', 'Salt', 'Inlet'],
      icon: 'spray',
      iconWrap: 'bg-[#78909C]',
    },
    {
      title: 'Small appliances',
      description: 'Mixer, induction cooktop, and vacuum — bench service where economical.',
      tags: ['Mixer', 'Induction', 'Vacuum'],
      icon: 'plug',
      iconWrap: 'bg-[#90A4AE]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Diagnostics',
      items: [
        { name: 'Error code map', desc: 'Maker-specific tables used before swapping guesses.' },
        { name: 'Leak trace', desc: 'Dye, pressure, and hose routing for hidden washer leaks.' },
        { name: 'Thermal checks', desc: 'Fridge loop temps across evaporator/condenser stages.' },
        { name: 'Earth leakage step', desc: 'Wet-area appliances tested on RCD/ELCB context.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Repairs',
      items: [
        { name: 'OEM-leaning parts', desc: 'Alternatives explained if OEM on long back-order.' },
        { name: 'Bearing & seal jobs', desc: 'Full drum job quoted with labour hours, not surprise mid-wash.' },
        { name: 'Board-level', desc: 'Relay/fuse paths before full PCB replace when sane.' },
        { name: 'Calibration', desc: 'Water level pressure hose and sensor relearn sequences.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Install aids',
      items: [
        { name: 'Level & anti-vibe', desc: 'Feet, transit bolts out, and rock test on spin.' },
        { name: 'Inlet hose spec', desc: 'Burst-proof hoses recommended on high pressure feeds.' },
        { name: 'Dedicated socket', desc: 'Advise 16A where code expects for large heaters.' },
        { name: 'Drain height', desc: 'Standpipe vs sink tap per machine manual.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Aftercare',
      items: [
        { name: 'Test cycle proof', desc: 'Spin/rinse or cool-down run captured before leaving.' },
        { name: 'Usage tips', desc: 'Load sizes and detergent dosing to extend pump life.' },
        { name: 'Warranty note', desc: 'Part serial + labour days on sheet.' },
        { name: 'Recycle path', desc: 'Old machine haul-away if purchased via add-on.' },
      ],
    },
  ],
  prices: [
    { title: 'Visit + diagnose', price: '₹299 – ₹599', note: 'Waived/adjusted when repair proceeds — stated per city.' },
    { title: 'WM drain pump job', price: '₹800 – ₹2,200', note: 'Labour + part typical band.', featured: true },
    { title: 'Fridge gas / loop', price: 'Quote after test', note: 'Compressor jobs separated from gas charge.' },
    { title: 'Geyser element', price: '₹600 – ₹1,800', note: 'Includes drain, fill, and air-bleed.' },
    { title: 'Microwave interlock set', price: '₹500 – ₹1,400', note: 'Safety-critical; HV area only for trained techs.' },
    { title: 'Extended labour', price: '₹150 – ₹300 / 30m', note: 'Post-approved scope — clocked transparently.' },
  ],
  toolsSectionLead: 'Bench discipline — fewer return visits.',
  tools: [
    { label: 'Insulation tester', icon: 'bolt' },
    { label: 'Clamp meter', icon: 'zap' },
    { label: 'Pressure / leak tools', icon: 'gauge' },
    { label: 'Torque & drivers', icon: 'wrench' },
    { label: 'Vacuum for glass', icon: 'wind' },
    { label: 'OEM adapters', icon: 'plug' },
    { label: 'Thermal probe', icon: 'thermometer' },
    { label: 'Software dongles', icon: 'radar' },
    { label: 'Spill mats', icon: 'droplets' },
    { label: 'PPE', icon: 'shield' },
  ],
  guaranteeIntro: 'Appliance repairs via Leads4U carry stated labour windows and parts return policy per maker rules.',
  stepMatchPhrase: 'technician',
  step4Closing: 'Test run done; invoice lists parts serials where applicable.',
  footerTitle: 'Ready to Book Appliance Repair?',
  footerSubtitle: 'Clear diagnostics first — then parts you approve.',
  primaryCtaLabel: 'Book Appliance Repair',
  finePrint: 'No credit card · cancel anytime · OEM-leaning parts where stocked',
  faqs: [
    { q: 'Do you repair under warranty brands?', a: 'Authorized channels for in-warranty; out-of-warranty is our sweet spot with clear part sourcing.' },
    { q: 'Will you dismantle built-in units?', a: 'Yes with kitchen safe guards — extra time quoted for panel removal.' },
    { q: 'What if the board is NLA?', a: 'We’ll quote retrofit options or honest replace vs repair economics.' },
    { q: 'Can I buy my own part?', a: 'Labour-only possible if part is correct SKU; no warranty on customer-supplied electronics.' },
    { q: 'Do you handle gas fridge refill?', a: 'Only where licensed and eco rules allow — city policy shown in app.' },
    { q: 'How do I prep for washer service?', a: 'Remove clothes, keep access side clear, and share error photo in booking.' },
  ],
} satisfies HomeServiceDetailConfig;

export const homeCleaningDetail = {
  slug: 'home-cleaning',
  metaTitle: 'Home Cleaning | Leads4U',
  metaDescription:
    'Deep and regular cleaning for all rooms — trained crews, safe chemistry, and checklists you can see on Leads4U.',
  heroLead: 'Rooms that ',
  heroItalic: 'feel',
  heroTail: ' reset',
  heroSubheading:
    'Deep and regular cleaning for all rooms — kitchen degrease, bath sanitise, and dust-down with supplies that match your floor types.',
  emergencyTitle: 'Guests arriving or handover tomorrow?',
  emergencyBody:
    'Add “express slot” in notes — we’ll propose crew size and hours so dry times still land before your deadline.',
  emergencyWhatsAppPrefill: 'Hi, I need home cleaning on short notice for guest / handover — what slots do you have?',
  categorySectionTitle: 'What we cover under Home Cleaning',
  categoryIntro: 'Choose a package anchor — final hours adjust on walkthrough with you.',
  categories: [
    {
      title: 'Deep clean',
      description: 'Top-to-bottom pass: skirting, switches, fans, and behind movable furniture.',
      tags: ['Top-down', 'Fans', 'Skirting'],
      icon: 'sparkles',
      iconWrap: 'bg-[#00897B]',
    },
    {
      title: 'Kitchen degrease',
      description: 'Hob, hood filters, backsplash, and cabinet finger zones with food-safe finish.',
      tags: ['Hob', 'Hood', 'Tiles'],
      icon: 'droplets',
      iconWrap: 'bg-[#00796B]',
    },
    {
      title: 'Bath sanitise',
      description: 'Fittings descaled, glass polished, and grout brightened within safe chemistry.',
      tags: ['Descale', 'Grout', 'Glass'],
      icon: 'bath',
      iconWrap: 'bg-[#00695C]',
    },
    {
      title: 'Floor care',
      description: 'Wood-safe damp mop, stone pH-aware clean, and carpet vacuum + spot.',
      tags: ['Wood', 'Stone', 'Carpet'],
      icon: 'layers',
      iconWrap: 'bg-[#004D40]',
    },
    {
      title: 'Move-in / out',
      description: 'Empty-home pass with balcony and cupboard internals on checklist.',
      tags: ['Cupboards', 'Balcony', 'Windows'],
      icon: 'house',
      iconWrap: 'bg-[#26A69A]',
    },
    {
      title: 'Regular upkeep',
      description: 'Weekly/bi-weekly lighter passes to maintain baseline hygiene.',
      tags: ['Weekly', 'Dust', 'Bins'],
      icon: 'wind',
      iconWrap: 'bg-[#4DB6AC]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Hygiene standards',
      items: [
        { name: 'Colour-coded cloths', desc: 'Bath vs kitchen segregation default on deep jobs.' },
        { name: 'Fresh mop heads', desc: 'Per home or sealed launder cycle — noted on scope.' },
        { name: 'Gloves & disposal', desc: 'Biohazard guidance if encounter pests — paused and escalated.' },
        { name: 'Ventilation', desc: 'Aerosol discipline; windows timed for cure and smell.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Surfaces',
      items: [
        { name: 'Glass streak control', desc: 'Two-step buff on mirrors and partitions.' },
        { name: 'Stainless direction', desc: 'Grain-aligned wipes to avoid micro scratches.' },
        { name: 'Wood damp policy', desc: 'Minimal moisture on veneered panels.' },
        { name: 'Stone pH test', desc: 'Acid cleaners avoided on marble/calcite.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Add-ons',
      items: [
        { name: 'Sofa vacuum + foam', desc: 'Fabric test patch first.' },
        { name: 'Balcony scrub', desc: 'Drain clear after pour.' },
        { name: 'Oven interior', desc: 'Soak trays; racks degreased offsite if needed.' },
        { name: 'Fridge empty clean', desc: 'Power-safe; food in cool bag per your prep.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Close-out',
      items: [
        { name: 'Checklist sign-off', desc: 'Room-by-room tick with you on deep jobs.' },
        { name: 'Waste bag tie', desc: 'Left by service door unless society rules differ.' },
        { name: 'Photo pack optional', desc: 'For landlord handover packages.' },
        { name: 'Reclean window', desc: '48h snag policy where package includes it.' },
      ],
    },
  ],
  prices: [
    { title: '1 BHK deep (indicative)', price: '₹2,800 – ₹4,800', note: 'Furnished vs empty adjusts hours.', featured: true },
    { title: '2 BHK deep', price: '₹3,800 – ₹6,500', note: 'Balcony/glass add-ons listed separately.' },
    { title: 'Kitchen-only blitz', price: '₹1,200 – ₹2,400', note: 'Hob + hood + tiles baseline.' },
    { title: 'Bath-only (2)', price: '₹900 – ₹1,800', note: 'Descale intensity varies.' },
    { title: 'Hourly crew', price: '₹299 – ₹499 / hr', note: 'Per person; min hours by pincode.' },
    { title: 'Move-out + oven', price: 'Package quote', note: 'Oven + cupboards + windows bundle.' },
  ],
  toolsSectionLead: 'Colour-coded kit — cross-contamination kept low.',
  tools: [
    { label: 'HEPA vacuums', icon: 'wind' },
    { label: 'Microfibre sets', icon: 'layers' },
    { label: 'Scrub decks', icon: 'sparkles' },
    { label: 'Glass tools', icon: 'droplets' },
    { label: 'Steam (where safe)', icon: 'thermometer' },
    { label: 'Grout brushes', icon: 'wrench' },
    { label: 'pH test strips', icon: 'gauge' },
    { label: 'Step ladders', icon: 'ruler' },
    { label: 'Floor machines', icon: 'radar' },
    { label: 'PPE & shoe covers', icon: 'shield' },
  ],
  guaranteeIntro: 'Cleaning packs on Leads4U include restage policy where package explicitly lists snag window.',
  stepMatchPhrase: 'cleaning crew',
  step4Closing: 'Checklist signed; tip optional — ratings help crews most.',
  footerTitle: 'Ready to Book Home Cleaning?',
  footerSubtitle: 'Deep and regular visits — crew-matched to your home size.',
  primaryCtaLabel: 'Book Home Cleaning',
  finePrint: 'No credit card · cancel anytime · supplies included unless noted',
  faqs: [
    { q: 'Do I need to provide detergents?', a: 'Standard packs bring crew kit; hypoallergenic or baby-safe on request in notes.' },
    { q: 'Are maids background-checked?', a: 'Partners commit to BGV on platform roster — flag society gate pass needs early.' },
    { q: 'What about pets?', a: 'Note breed/temperament; we’ll assign pet-comfort crews and avoid aerosols near cages.' },
    { q: 'Can you clean marble?', a: 'Yes — pH-safe chemistry only; acidic descalers skipped.' },
    { q: 'How long does a deep clean take?', a: 'Typical 1 BHK: 3–5 crew-hours; we confirm after photos.' },
    { q: 'Do you move heavy furniture?', a: 'Light slide only; heavy lifts need your help or a two-person add-on.' },
  ],
} satisfies HomeServiceDetailConfig;

export const pestControlDetail = {
  slug: 'pest-control',
  metaTitle: 'Pest Control | Leads4U',
  metaDescription:
    'Targeted treatment for cockroaches, termites, rodents, and more — scheduled plans and safety-first application on Leads4U.',
  heroLead: 'Pests ',
  heroItalic: 'out',
  heroTail: ', peace in',
  heroSubheading:
    'Targeted treatment for common pests — gel + spray programs where appropriate, termite drill schedules, and rodent proofing with follow-ups you can plan.',
  emergencyTitle: 'Sudden cockroach surge or rodent noise in false ceiling?',
  emergencyBody:
    'Flag severity in booking — we’ll suggest first knock-down visit plus longer plan for resistance management.',
  emergencyWhatsAppPrefill: 'Hi, I need pest control urgently — cockroaches / rodents — soonest visit?',
  categorySectionTitle: 'What we cover under Pest Control',
  categoryIntro: 'Pick the pest family — technician selects chemistry tier only after site risk check.',
  categories: [
    {
      title: 'General crawling (GC)',
      description: 'Kitchen and bath harbourage treatment with crack-and-crevice focus.',
      tags: ['Gel', 'IRAC', 'Crack'],
      icon: 'bug',
      iconWrap: 'bg-[#33691E]',
    },
    {
      title: 'Flying insects',
      description: 'Mist / ULV where allowed plus breeding-site advice for stagnant water.',
      tags: ['ULV', 'Larvae', 'Source'],
      icon: 'wind',
      iconWrap: 'bg-[#558B2F]',
    },
    {
      title: 'Termite soil & wall',
      description: 'Drill-inject along plinth, wood contact points, and garden fence lines.',
      tags: ['Drill', 'Barrier', 'Wood'],
      icon: 'treePine',
      iconWrap: 'bg-[#689F38]',
    },
    {
      title: 'Rodent management',
      description: 'Snap stations, glue boards (signed consent), and proofing gaps with metal mesh.',
      tags: ['Proofing', 'Stations', 'Follow-up'],
      icon: 'house',
      iconWrap: 'bg-[#7CB342]',
    },
    {
      title: 'Bed bugs & ticks',
      description: 'Residual cycles + mattress seam focus; mattress encasement advice.',
      tags: ['Seams', 'Residual', 'Encase'],
      icon: 'layers',
      iconWrap: 'bg-[#9CCC65]',
    },
    {
      title: 'Commercial kitchens',
      description: 'Night slots, SS-safe chemistry, and logbook for audits.',
      tags: ['Night', 'SS-safe', 'Logs'],
      icon: 'shield',
      iconWrap: 'bg-[#827717]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Safety',
      items: [
        { name: 'Allergy & pet check', desc: 'Birds/fish tanks covered or relocated guidance pre-spray.' },
        { name: 'Child lock plan', desc: 'Gel-only zones where aerosol restricted.' },
        { name: 'Ventilation SOP', desc: 'Re-entry time communicated and posted on fridge note.' },
        { name: 'PPE & MSDS', desc: 'On request for society or commercial H&S files.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Cockroach programs',
      items: [
        { name: 'Harbourage map', desc: 'Hinges, motors, and conduit voids on kitchen map.' },
        { name: 'Rotation plan', desc: 'Active swaps across visits to manage resistance.' },
        { name: 'Drain pour', desc: 'Biocide gels where plumbing is entry vector.' },
        { name: 'Monitoring glue', desc: 'Optional post-7-day catch count review.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Termite',
      items: [
        { name: 'Mud tube scrape', desc: 'Expose live channels before injection.' },
        { name: 'Plinth grid', desc: 'Spacing per soil type; depth logged.' },
        { name: 'Wood touch-ups', desc: 'Localised borate brush on exposed ends when spec allows.' },
        { name: 'Warranty visits', desc: 'Annual inspection slots on premium packages.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Rodents',
      items: [
        { name: 'Line walk', desc: 'Roof, utility, and pipe chase survey for entry gaps.' },
        { name: 'Metal mesh', desc: 'Chew-proof on drain grilles and low vents.' },
        { name: 'Trap cadence', desc: 'Check schedule until catch rate hits zero.' },
        { name: 'Dead rodent SOP', desc: 'Ceiling tile protocol with building manager if needed.' },
      ],
    },
  ],
  prices: [
    { title: '1 BHK GC treatment', price: '₹1,200 – ₹2,400', note: 'Single visit knock-down; AMC cheaper per visit.', featured: true },
    { title: '2 BHK GC', price: '₹1,600 – ₹3,200', note: 'Heavy infestation may need second visit — quoted upfront.' },
    { title: 'Termite (per running ft)', price: '₹45 – ₹120', note: 'Drill depth + chemical tier drives band.' },
    { title: 'Rodent proofing visit', price: '₹1,500 – ₹4,000', note: 'Mesh + stations; follow-ups packaged.' },
    { title: 'Bed bug cycle (3 visits)', price: 'Package quote', note: 'Room count + fabric density.' },
    { title: 'Commercial kitchen monthly', price: 'Contract', note: 'Night hours + logbook included.' },
  ],
  toolsSectionLead: 'Application gear calibrated — drift and waste minimised.',
  tools: [
    { label: 'ULV / misting', icon: 'spray' },
    { label: 'Crack & crevice wand', icon: 'sprayCan' },
    { label: 'Power drill set', icon: 'bolt' },
    { label: 'Rodent stations', icon: 'shield' },
    { label: 'Torches & mirrors', icon: 'lightbulb' },
    { label: 'PPE suits', icon: 'shield' },
    { label: 'Measuring wheel', icon: 'ruler' },
    { label: 'Foam seal gun', icon: 'layers' },
    { label: 'IR temp (nest hints)', icon: 'thermometer' },
    { label: 'Customer signage', icon: 'house' },
  ],
  guaranteeIntro: 'Pest programs on Leads4U list revisit windows where package includes free callback for same pest class.',
  stepMatchPhrase: 'pest technician',
  step4Closing: 'Re-entry time confirmed; service report with active ingredients on request.',
  footerTitle: 'Ready to Book Pest Control?',
  footerSubtitle: 'Targeted plans — not one-bottle-fits-all.',
  primaryCtaLabel: 'Book Pest Control',
  finePrint: 'No credit card · cancel anytime · MSDS on request',
  faqs: [
    { q: 'Do I need to leave the house?', a: 'Depends on chemistry and ventilation — technician states re-entry minutes on sheet.' },
    { q: 'Are chemicals safe for pets?', a: 'We map pet zones and adjust formulation/route; some visits need brief pet relocation.' },
    { q: 'Why a second visit?', a: 'Heavy GC load or egg cases hatching — second hit timed, often within 10–14 days.' },
    { q: 'Do you remove termite mud permanently?', a: 'Tube scrape is part of treatment; structural timber repair is separate trade.' },
    { q: 'What if I’m in a high-rise?', a: 'Drill noise windows coordinated with society; balcony grid for soil-less plinths.' },
    { q: 'Is there a smell?', a: 'Some solvent carriers smell short-term; water-based options where sensitivity flagged.' },
  ],
} satisfies HomeServiceDetailConfig;

export const waterproofingDetail = {
  slug: 'waterproofing',
  metaTitle: 'Waterproofing | Leads4U',
  metaDescription:
    'Terrace, wall, and bathroom waterproofing — structured systems, flood tests, and documented layers on Leads4U.',
  heroLead: 'Keep water ',
  heroItalic: 'outside',
  heroTail: ', where it belongs',
  heroSubheading:
    'Terrace and wall seepage solutions — multi-layer systems, correct falls, and flood tests before you re-tile or repaint.',
  emergencyTitle: 'Active drip after rain or bubbling paint spreading fast?',
  emergencyBody:
    'We’ll advise temporary catch and divert steps on call while scheduling membrane crew — photo/video speeds triage.',
  emergencyWhatsAppPrefill: 'URGENT: Active seepage / dripping from ceiling or terrace — need waterproofing assessment ASAP.',
  categorySectionTitle: 'What we cover under Waterproofing',
  categoryIntro: 'Choose the surface class — each path ends in a written layer stack and test record.',
  categories: [
    {
      title: 'Terrace liquid systems',
      description: 'Primer, reinforcement, and UV-stable topcoat cycles with outlet detail.',
      tags: ['Primer', 'Mesh', 'UV coat'],
      icon: 'house',
      iconWrap: 'bg-[#01579B]',
    },
    {
      title: 'Bathroom wet zones',
      description: 'Polymer slurry under screed, angle fillets, and pipe sleeve seals.',
      tags: ['Sleeves', 'Fillet', 'Flood test'],
      icon: 'droplets',
      iconWrap: 'bg-[#0277BD]',
    },
    {
      title: 'Basement & tanking',
      description: 'Negative-side crystalline or positive-side membrane per hydrostatic risk.',
      tags: ['Crystalline', 'Drain', 'Membrane'],
      icon: 'layers',
      iconWrap: 'bg-[#0288D1]',
    },
    {
      title: 'Exterior wall damp',
      description: 'Breathable creams vs film systems chosen from salt / paint failure pattern.',
      tags: ['Breathable', 'Salt', 'Film'],
      icon: 'shield',
      iconWrap: 'bg-[#039BE5]',
    },
    {
      title: 'Expansion & cracks',
      description: 'Routing, bond breaker, and flexible seal before overcoat.',
      tags: ['Routing', 'PU', 'Movement'],
      icon: 'gitBranch',
      iconWrap: 'bg-[#0277BD]',
    },
    {
      title: 'Metal & gutter detail',
      description: 'Flashing overlaps, drip edges, and downpipe shoe fixes stopping reverse climb.',
      tags: ['Flashing', 'Drip', 'Shoe'],
      icon: 'wrench',
      iconWrap: 'bg-[#01579B]',
    },
  ],
  checkGroups: [
    {
      emoji: '🔴',
      title: 'Diagnosis',
      items: [
        { name: 'Moisture mapping', desc: 'Probe grid to separate plumbing vs envelope damp.' },
        { name: 'Flood test (bath)', desc: 'Plugged tray 24h where society allows wet test.' },
        { name: 'Core caution', desc: 'As-built slab thickness checks before heavy scarify.' },
        { name: 'Photo chain', desc: 'Date-stamped progress for warranty pack.' },
      ],
    },
    {
      emoji: '🔵',
      title: 'Terrace execution',
      items: [
        { name: 'Outlet choke clear', desc: 'Drainage before membrane — hidden cause of repeats.' },
        { name: 'Priming', desc: 'Dust-free surface; consumption rate logged per m².' },
        { name: 'Reinforcement laps', desc: 'Overlap widths per TDS; no dry laps.' },
        { name: 'Flood / hose test', desc: 'Post-cure check before tiles or pavers return.' },
      ],
    },
    {
      emoji: '🟢',
      title: 'Bathroom rehabs',
      items: [
        { name: 'Jack-hammer discipline', desc: 'Depth stops to protect structural slab.' },
        { name: 'Pipe chase packing', desc: 'Non-shrink + flexible combo around penetrations.' },
        { name: 'Threshold bridges', desc: 'Wet room gradients to drain without trip lip.' },
        { name: 'Curing guards', desc: 'No foot traffic window posted at handover.' },
      ],
    },
    {
      emoji: '🟠',
      title: 'Warranty pack',
      items: [
        { name: 'Layer datasheet PDF', desc: 'Batch numbers captured on critical coats.' },
        { name: 'Maintenance calendar', desc: 'UV re-topcoat years for exposed liquid systems.' },
        { name: 'Penetration addendum', desc: 'Future AC/HWT cuts — reseal spec provided.' },
        { name: 'Insurance letter', desc: 'Narrative + photos for claim support where applicable.' },
      ],
    },
  ],
  prices: [
    { title: 'Terrace survey', price: '₹999 – ₹2,500', note: 'Credited to job if you proceed within 30 days.' },
    { title: 'Liquid terrace (per sq ft)', price: '₹45 – ₹120', note: 'Prep depth + mesh + UV tier drives band.', featured: true },
    { title: 'Bathroom pack (typical)', price: '₹18,000 – ₹45,000', note: 'Jack + slurry + screed + flood test in scope.' },
    { title: 'Negative-side crystalline', price: '₹35 – ₹95 / sq ft', note: 'Basement risk tier after probe.' },
    { title: 'Crack injection (LM)', price: '₹350 – ₹900', note: 'Epoxy vs PU chosen by crack dynamics.' },
    { title: 'Emergency tarp + drain', price: '₹1,500 – ₹5,000', note: 'Temporary only — not substitute for membrane.' },
  ],
  toolsSectionLead: 'Test-led installs — fewer comebacks after first monsoon.',
  tools: [
    { label: 'Moisture meters', icon: 'droplets' },
    { label: 'Holiday detectors', icon: 'radar' },
    { label: 'Scarifiers / grinders', icon: 'bolt' },
    { label: 'Heat gun / dryers', icon: 'thermometer' },
    { label: 'Flood plugs', icon: 'bath' },
    { label: 'Notched spreaders', icon: 'ruler' },
    { label: 'Pressure pots', icon: 'gauge' },
    { label: 'Injection pumps', icon: 'wrench' },
    { label: 'Core bits', icon: 'gitBranch' },
    { label: 'PPE & vapour masks', icon: 'shield' },
  ],
  guaranteeIntro: 'Waterproofing jobs on Leads4U carry membrane manufacturer alignment plus platform mediation on workmanship disputes.',
  stepMatchPhrase: 'waterproofing crew',
  step4Closing: 'Flood test record signed; maintenance calendar handed over.',
  footerTitle: 'Ready to Book Waterproofing?',
  footerSubtitle: 'Terrace, bath, and wall systems — documented layers.',
  primaryCtaLabel: 'Book Waterproofing',
  finePrint: 'No credit card · cancel anytime · TDS batches logged on request',
  faqs: [
    { q: 'Will you break my tiles?', a: 'Bathroom rehab packages expect tile lift to membrane; relay is quoted as line items.' },
    { q: 'How long before I can use the bath?', a: 'Cure + flood test windows vary by chemistry — printed on handover sheet.' },
    { q: 'Does paint stop seepage?', a: 'Film paints trap moisture; we choose breathable or fix source first.' },
    { q: 'What if seepage is actually plumbing?', a: 'We halt membrane spend and refer/plumb isolate — moisture map guides the call.' },
    { q: 'Is there a monsoon warranty?', a: 'Written slab/terrace warranties state first-pass rain observation window — details in quote.' },
    { q: 'Do you handle STP / tank farms?', a: 'Commercial tanks quoted separately with confined-space rules.' },
  ],
} satisfies HomeServiceDetailConfig;
